DROP DATABASE IF EXISTS tstdb;
CREATE DATABASE IF NOT EXISTS tstdb
CHARACTER SET utf8 COLLATE utf8_general_ci;
USE tstdb;
DROP TABLE IF EXISTS tsttbl;
CREATE TABLE IF NOT EXISTS tsttbl (
 `id` BIGINT PRIMARY KEY NOT NULL UNIQUE
) CHARACTER SET utf8 COLLATE utf8_general_ci;
